import type { ResourceLink } from '../topic-guides';
import type { TopicGuide } from '../topic-guides';

function lc(slug: string, label = 'LeetCode problem'): ResourceLink {
	return { kind: 'problem', label, href: `https://leetcode.com/problems/${slug}/` };
}

function gfg(path: string, label = 'GFG problem'): ResourceLink {
	return { kind: 'problem', label, href: `https://www.geeksforgeeks.org/${path}` };
}

function tuf(path: string, label = 'takeUforward article'): ResourceLink {
	return { kind: 'read', label, href: `https://takeuforward.org/${path}` };
}

function nc(path: string, label = 'NeetCode (video + practice)'): ResourceLink {
	return { kind: 'explainer', label, href: `https://neetcode.io/problems/${path}` };
}

function lesson(blurb: string, links: ResourceLink[], extra: Partial<TopicGuide> = {}): TopicGuide {
	return { blurb, ...extra, links };
}

export const DSA_LESSONS: Record<string, TopicGuide> = {
	'Merge Sort': lesson('Stable n log n sort. Split, sort halves, merge. The merge step is also how you count inversions and reverse pairs.', [gfg('merge-sort/'), tuf('data-structure/merge-sort-algorithm')], { complexity: 'O(n log n) time, O(n) space', layman: 'Split the list in half until pieces are tiny, sort those, then zip them back together in order.' }),
	'Quick Sort': lesson('Pick a pivot, partition in place, recurse. Average n log n, worst n² if the pivot is always worst. Know Lomuto vs Hoare enough to implement one.', [gfg('quick-sort/'), tuf('data-structure/quick-sort-algorithm')], { complexity: 'Average O(n log n), worst O(n²), O(log n) stack' }),
	'Sort Colors': lesson('Dutch national flag: one pass, three pointers for 0/1/2. If you allocate a count array you missed the interview point.', [lc('sort-colors'), tuf('data-structure/sort-an-array-of-0s-1s-and-2s/')], { complexity: 'O(n) time, O(1) space' }),
	'Remove Duplicates from Sorted Array': lesson('Read/write two pointers on a sorted array. Write index only moves when the value is new. Return the write length.', [lc('remove-duplicates-from-sorted-array')]),
	'Rotate Array': lesson('Reverse all, reverse first k, reverse rest. Three reverses beat an extra array, and k %= n first.', [lc('rotate-array')]),
	'Move Zeroes': lesson('Write pointer for non-zeros, then fill zeros. Relative order of non-zeros must survive.', [lc('move-zeroes')]),
	'Missing Number': lesson('XOR 0..n with every index and value, or Gauss sum. Cyclic sort also works: put n at n.', [lc('missing-number')]),
	'Max Consecutive Ones': lesson('Count streaks of 1, reset on 0. Warm-up for Max Consecutive Ones III where you may flip zeros.', [lc('max-consecutive-ones')]),
	'Two Sum': lesson('One pass hash: value → index. If target - x is already in the map, you are done. Sorting + two pointers also works if you may reorder.', [lc('two-sum'), tuf('data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/')], { complexity: 'O(n) time, O(n) space', layman: 'You are looking for two numbers that add to a target. Remember every number you have already seen.' }),
	'Majority Element': lesson('Boyer–Moore: candidate and count. The majority (> n/2) cannot be cancelled. Verify if the prompt does not guarantee one.', [lc('majority-element'), tuf('data-structure/find-the-majority-element-that-occurs-more-than-n-2-times/')]),
	'Maximum Subarray': lesson('Kadane: running sum, reset when negative. The answer is the max of those running sums. Empty-subarray rules depend on the prompt.', [lc('maximum-subarray'), tuf('data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/')], { complexity: 'O(n) time, O(1) space' }),
	'Best Time to Buy and Sell Stock': lesson('Track the minimum price so far; sell today vs that min. One transaction. II/III/cooldown are DP on that idea.', [lc('best-time-to-buy-and-sell-stock')]),
	'Next Permutation': lesson('Find the rightmost ascent, swap with the next larger on the right, reverse the suffix. That is the next lexicographic permutation.', [lc('next-permutation'), tuf('data-structure/next_permutation-find-next-lexicographically-greater-permutation/')]),
	'Longest Consecutive Sequence': lesson('Put numbers in a set. Only start a streak from n if n-1 is missing. Then the whole algorithm is O(n).', [lc('longest-consecutive-sequence')]),
	'Set Matrix Zeroes': lesson('Use first row/column as markers so you do not need O(m+n) extra memory. Mark first, then zero, then the first row/column themselves.', [lc('set-matrix-zeroes'), tuf('data-structure/set-matrix-zero/')]),
	'Rotate Image': lesson('Transpose, then reverse each row (clockwise). Do it in place. Four-way swap also works if you like indices.', [lc('rotate-image')]),
	'Spiral Matrix': lesson('Walk a shrinking bounding box: right, down, left, up. Watch the single-row and single-column traps when the box collapses.', [lc('spiral-matrix')]),
	'Pascal\'s Triangle': lesson('Each number is left-parent + right-parent. Row i has i+1 entries. Combinations C(n,k) is the same triangle.', [lc('pascals-triangle')]),
	'Majority Element II': lesson('At most two values can exceed n/3. Boyer–Moore with two candidates, then a verify pass.', [lc('majority-element-ii')]),
	'Product of Array Except Self': lesson('Prefix products from the left, suffix from the right. No division. The output array can store one of the two passes.', [lc('product-of-array-except-self')]),
	'Subarray Sum Equals K': lesson('Prefix sum + hash of frequencies. If prefix - k was seen, those starts work. Zeros and negatives make sliding window illegal.', [lc('subarray-sum-equals-k')]),
	'Rearrange Array Elements by Sign': lesson('Two write pointers (pos/neg) into a new array, or two read pointers if you may allocate. Signs alternate; counts are equal in the LC version.', [lc('rearrange-array-elements-by-sign')]),
	'4Sum': lesson('Sort, fix two numbers, two-pointer the rest. Skip duplicates at every level. Same skeleton as 3Sum with one extra loop.', [lc('4sum')]),
	'Merge Intervals': lesson('Sort by start. If the next start ≤ current end, extend the end; else emit and start a new interval.', [lc('merge-intervals'), tuf('data-structure/merge-overlapping-sub-intervals/')]),
	'Merge Sorted Array': lesson('Fill nums1 from the back. Three pointers: ends of both arrays and the write index. Avoids the extra buffer.', [lc('merge-sorted-array')]),
	'Find the Duplicate Number': lesson('Array as a linked list (index → value). Floyd cycle finds the duplicate without mutating and without extra space.', [lc('find-the-duplicate-number')]),
	'Missing and Repeating Number': lesson('Math (sum and sum of squares) or XOR in two groups, or a boolean mark in-place. GFG states it as one missing + one repeating.', [gfg('problems/find-missing-and-repeating2512/1')]),
	'Reverse Pairs': lesson('Count i < j with nums[i] > 2*nums[j] during merge sort. The merge is the count, not a Fenwick unless you want one.', [lc('reverse-pairs')]),
	'Maximum Product Subarray': lesson('Track min and max ending here because a negative flips the product. Zeros reset the streak.', [lc('maximum-product-subarray')]),
	'Count Inversions': lesson('Merge sort counting: when you take from the right half, all leftover left-half items invert with it.', [gfg('problems/inversion-of-array-1587115620/1')]),
	'Contains Duplicate': lesson('A set. If insert fails, you have seen it. Sorting also works; interviews want the set unless they ban extra memory.', [lc('contains-duplicate')]),
	'Valid Anagram': lesson('Count 26 letters (or a map for unicode). Sorting both strings is the lazy check.', [lc('valid-anagram')]),
	'Group Anagrams': lesson('Key = sorted letters, or a 26-count tuple. Map key → list of words.', [lc('group-anagrams')]),
	'Longest Subarray with Sum K': lesson('For positives, shrink a window. For negatives, you need the prefix-hash method, not two pointers.', [gfg('problems/longest-sub-array-with-sum-k0809/1')]),
	'Count Subarrays with XOR K': lesson('Prefix XOR + hash. Same identity as subarray-sum: prefix ^ k seen means a subarray XOR equals k.', [gfg('problems/count-subarray-with-given-xor/1')]),
	'Encode and Decode Strings': lesson('Length-prefix each string (3#abc) so decode cannot confuse delimiters inside the payload. LC is premium; NeetCode hosts it.', [nc('string-encode-and-decode')]),
	'Valid Palindrome': lesson('Two pointers, skip non-alnum, compare lowercased. Do not allocate a cleaned copy unless you are stuck.', [lc('valid-palindrome')]),
	'Two Sum II (sorted)': lesson('Opposite-end pointers on a sorted array. Move the side that makes the sum closer to target. Constant extra space.', [lc('two-sum-ii-input-array-is-sorted')]),
	'3Sum': lesson('Sort, fix i, two-pointer the pair. Skip duplicate i/lo/hi or you emit the same triplet twice.', [lc('3sum'), tuf('data-structure/3-sum-find-triplets-that-add-up-to-a-zero/')]),
	'Container With Most Water': lesson('Start at both ends. Area is min(height) * width. Move the shorter wall; the longer one cannot improve until the short one does.', [lc('container-with-most-water')]),
	'Trapping Rain Water': lesson('Water at i is min(leftMax, rightMax) - height[i]. Two-pointer version keeps leftMax/rightMax and walks the smaller side.', [lc('trapping-rain-water'), tuf('data-structure/trapping-rainwater/')], { complexity: 'O(n) time, O(1) two-pointer' }),
	'Remove Duplicates from Sorted Array II': lesson('Allow at most two copies. Write pointer; compare with write-2, not with the previous write.', [lc('remove-duplicates-from-sorted-array-ii')]),
	'Is Subsequence': lesson('One pointer on s, walk t. If s is consumed, it is a subsequence. Binary search on index lists if you must answer many s for one t.', [lc('is-subsequence')]),
	'Longest Substring Without Repeating Characters': lesson('Window + last-index map. When s[r] repeats, move l to last[s[r]]+1. Answer is max window length.', [lc('longest-substring-without-repeating-characters')]),
	'Longest Repeating Character Replacement': lesson('Window; you may change k chars. If window - maxFreq > k, shrink. The maxFreq char is the one you keep.', [lc('longest-repeating-character-replacement')]),
	'Permutation in String': lesson('Fixed window the size of s1, compare 26-count with s1. Slide, decrement left, increment right.', [lc('permutation-in-string')]),
	'Minimum Window Substring': lesson('Need-map of t. Expand r until formed==need, then shrink l and record the best. This is the hard sliding-window template.', [lc('minimum-window-substring')]),
	'Minimum Size Subarray Sum': lesson('Positive numbers: expand until sum ≥ target, shrink, keep min length. Negatives would break this.', [lc('minimum-size-subarray-sum')]),
	'Max Consecutive Ones III': lesson('Window of 1s where zeros in the window ≤ k. Same as longest window with at most k zeros.', [lc('max-consecutive-ones-iii')]),
	'Fruit Into Baskets': lesson('Longest subarray with at most 2 distinct values. Map of counts; shrink when distinct > 2.', [lc('fruit-into-baskets')]),
	'Sliding Window Maximum': lesson('Deque of decreasing indices. Front is the max. Pop back if smaller than the new value; pop front if out of window.', [lc('sliding-window-maximum')], { layman: 'Keep the biggest value in the current slice on the front of a queue that only holds useful candidates.' }),
	'Binary Search': lesson('While lo ≤ hi, mid = lo+((hi-lo)//2). Decide which half dies. Off-by-one lives in the comparison, not the mid formula.', [lc('binary-search')]),
	'Search Insert Position': lesson('Lower bound: first index ≥ target. Same binary search, hi = mid-1 when nums[mid] ≥ target.', [lc('search-insert-position')]),
	'Find First and Last Position of Element': lesson('Two binary searches: first ≥ target, first ≥ target+1. Missing → [-1,-1].', [lc('find-first-and-last-position-of-element-in-sorted-array')]),
	'Search in Rotated Sorted Array': lesson('One half of [lo,mid] is always sorted. If target is in the sorted half, throw the other half away.', [lc('search-in-rotated-sorted-array')]),
	'Search in Rotated Sorted Array II': lesson('Duplicates: if nums[lo]==nums[mid]==nums[hi], lo++/hi--. Otherwise same as rotated search.', [lc('search-in-rotated-sorted-array-ii')]),
	'Find Minimum in Rotated Sorted Array': lesson('The min is the rotation pivot. If nums[mid] > nums[hi], min is to the right; else mid might be the min.', [lc('find-minimum-in-a-rotated-sorted-array')]),
	'Single Element in a Sorted Array': lesson('Pairs sit on even/odd indices until the single. Binary search on index parity.', [lc('single-element-in-a-sorted-array')]),
	'Find Peak Element': lesson('If mid < mid+1, a peak exists on the right (the array \'goes up\'). Any peak is accepted.', [lc('find-peak-element')]),
	'Koko Eating Bananas': lesson('Binary search the eating speed. Feasibility: hours_needed(mid) ≤ h. Search the minimum true speed.', [lc('koko-eating-bananas')]),
	'Capacity To Ship Packages Within D Days': lesson('Binary search capacity. Greedy pack days at that capacity. Minimize capacity that fits in D days.', [lc('capacity-to-ship-packages-within-d-days')]),
	'Split Array Largest Sum': lesson('Same search-on-answer: minimize the max bucket sum if you split into k subarrays.', [lc('split-array-largest-sum')]),
	'Aggressive Cows': lesson('Place cows with binary-searched min distance. Greedy: put next cow at the first stall that respects the gap.', [gfg('problems/aggressive-cows/0')]),
	'Book Allocation': lesson('Minimize the max pages any student gets. Feasibility is a greedy scan of the array.', [gfg('problems/allocate-minimum-number-of-pages0937/1')]),
	'Median of Two Sorted Arrays': lesson('Binary search the partition of the shorter array so left_max ≤ right_min on both sides. O(log min(m,n)).', [lc('median-of-two-sorted-arrays')], { complexity: 'O(log min(m,n)) time' }),
	'Search a 2D Matrix': lesson('Treat the matrix as a flattened sorted array, or binary search rows then columns.', [lc('search-a-2d-matrix')]),
	'Search a 2D Matrix II': lesson('Start top-right: left if too big, down if too small. Each step kills a row or a column.', [lc('search-a-2d-matrix-ii')]),
	'Time Based Key-Value Store': lesson('Map key → sorted (timestamp, value). Binary search the last timestamp ≤ query.', [lc('time-based-key-value-store')]),
	'Reverse Words in a String': lesson('Trim, split on spaces, reverse the word list, join. In-place: reverse the whole string, then reverse each word.', [lc('reverse-words-in-a-string')]),
	'Longest Common Prefix': lesson('Vertical scan or binary search on prefix length. Sorting and comparing first/last also works.', [lc('longest-common-prefix')]),
	'Isomorphic Strings': lesson('Two maps (or arrays): s→t and t→s. A letter cannot map to two letters either way.', [lc('isomorphic-strings')]),
	'Roman to Integer': lesson('Add values; if a smaller value precedes a larger one, subtract it instead (IV, IX, XL…).', [lc('roman-to-integer')]),
	'String to Integer (atoi)': lesson('Skip space, read sign, accumulate digits, clamp to 32-bit. Interview cares about overflow and junk after digits.', [lc('string-to-integer-atoi')]),
	'Compare Version Numbers': lesson('Split on \'.\', compare integer parts, missing parts are 0. Do not compare as strings.', [lc('compare-version-numbers')]),
	'Count and Say': lesson('Run-length the previous term. n=1 is \'1\'. Implementation, not a trick.', [lc('count-and-say')]),
	'Longest Palindromic Substring': lesson('Expand around each center (odd and even). Manacher is overkill unless they ask linear time.', [lc('longest-palindromic-substring')]),
	'Implement strStr': lesson('Naive is fine; KMP prefix table is the \'I know strings\' version. Haystack window vs needle.', [lc('find-the-index-of-the-first-occurrence-in-a-string')]),
	'Valid Parenthesis String': lesson('Track a range of possible open-counts because \'*\' can be \'(\', \')\' or empty. Or two passes greedy.', [lc('valid-parenthesis-string')]),
	'Minimum Characters to Make Palindrome': lesson('KMP on s + \'#\' + reverse(s). The prefix table at the end tells you the longest palindromic prefix; add the rest on the front.', [gfg('problems/minimum-characters-to-be-added-at-front-to-make-string-palindrome/1')]),
	'Repeated String Match': lesson('Repeat a until it is longer than b, check contains; one more repeat covers the wrap. Then KMP.', [lc('repeated-string-match')]),
	'Reverse Linked List': lesson('Three pointers: prev, curr, next. Or recurse on the rest and point rest.next = head.', [lc('reverse-linked-list'), tuf('data-structure/reverse-a-linked-list/')]),
	'Middle of the Linked List': lesson('Slow/fast. Fast at 2x. When fast dies, slow is the middle (second middle if even, per LC).', [lc('middle-of-the-linked-list')]),
	'Merge Two Sorted Lists': lesson('Dummy head. Always take the smaller node. Attach the leftover tail at the end.', [lc('merge-two-sorted-lists')]),
	'Remove Nth Node From End': lesson('Dummy + gap of n between two pointers. Advance first n+1, then walk together, then skip next.', [lc('remove-nth-node-from-end-of-list')]),
	'Linked List Cycle': lesson('Floyd: slow/fast. If they meet, there is a cycle. No extra set required.', [lc('linked-list-cycle'), tuf('data-structure/detect-a-cycle-in-a-linked-list/')]),
	'Linked List Cycle II': lesson('After they meet, put one pointer at head. Same speed until they meet: that node is the cycle start.', [lc('linked-list-cycle-ii')]),
	'Intersection of Two Linked Lists': lesson('Switch heads when you hit null (a+b = b+a). They meet at the intersection or at null.', [lc('intersection-of-two-linked-lists')]),
	'Palindrome Linked List': lesson('Slow/fast to mid, reverse the second half, compare. Restore if you are polite.', [lc('palindrome-linked-list')]),
	'Odd Even Linked List': lesson('Split odd/even index chains, then concat. Index, not value.', [lc('odd-even-linked-list')]),
	'Rotate List': lesson('Count length, k %= n, connect tail to head, walk n-k, break. Circular then cut.', [lc('rotate-list')]),
	'Add Two Numbers': lesson('Dummy, carry. Digits are already reversed. Keep going while either list or carry remains.', [lc('add-two-numbers')]),
	'Copy List with Random Pointer': lesson('Hash old→new, then fill next/random. Interleave copies in the original list if they ban extra maps.', [lc('copy-list-with-random-pointer')]),
	'Flattening of Linked List': lesson('Merge two sorted child-lists bottom-up (like merge sort). Child pointer is the \'down\' chain.', [gfg('problems/flattening-a-linked-list/1')]),
	'Sort List': lesson('Merge sort on a list: split with slow/fast, sort halves, merge. Heap also works; they want merge sort.', [lc('sort-list')]),
	'Reorder List': lesson('Mid, reverse second half, weave L0, Ln, L1, Ln-1…', [lc('reorder-list')]),
	'Reverse Nodes in K Group': lesson('Count k, reverse that block, recurse/iterate the rest. Dummy head keeps the join clean.', [lc('reverse-nodes-in-k-group')]),
	'Merge K Sorted Lists': lesson('Min-heap of k heads, or divide-and-conquer merge. Heap is n log k.', [lc('merge-k-sorted-lists')], { complexity: 'O(n log k) with a heap' }),
	'Subsets': lesson('Backtrack: include or skip each index. Or iteratively double the answer by appending nums[i] to existing subsets.', [lc('subsets')]),
	'Subsets II': lesson('Sort, skip duplicate values at the same depth so duplicate subsets never start.', [lc('subsets-ii')]),
	'Combination Sum': lesson('Reuse the same index (unbounded). Recurse i, not i+1. Sort to prune when candidates[i] > remain.', [lc('combination-sum')]),
	'Combination Sum II': lesson('Each number once. Sort and skip duplicates at a depth, like Subsets II.', [lc('combination-sum-ii')]),
	'Permutations': lesson('Swap-in-place or a used[] array. n! leaves. Next permutation is a different problem.', [lc('permutations')]),
	'Palindrome Partitioning': lesson('DFS cuts; only recurse if s[i:j] is a palindrome. Expand or DP palindrome table if you want speed.', [lc('palindrome-partitioning')]),
	'Word Search': lesson('DFS from each cell, mark visited on the board (or a set), unmark on return. Trie upgrade is Word Search II.', [lc('word-search')]),
	'N-Queens': lesson('Place one queen per row. Arrays/bitmasks for col, diag, anti-diag. Record the board when row==n.', [lc('n-queens'), tuf('data-structure/n-queen-problem-return-all-distinct-solutions-to-the-n-queens-puzzle/')]),
	'Sudoku Solver': lesson('Find empty, try 1–9, check row/col/box. Recurse; backtrack on failure. Bitmasks if you want it fast.', [lc('sudoku-solver')]),
	'Letter Combinations of a Phone Number': lesson('Map digit → letters. Backtrack building a string of length digits.length.', [lc('letter-combinations-of-a-phone-number')]),
	'Generate Parentheses': lesson('Add \'(\' if open < n, \')\' if close < open. That invariant is the whole problem.', [lc('generate-parentheses')]),
	'Word Break II': lesson('DFS with memo of index → list of sentences. A boolean Word Break DP tells you if a suffix is even possible.', [lc('word-break-ii')]),
	'Rat in a Maze': lesson('DFS in four directions, mark visited, collect paths as strings. GFG wants all paths in lex order.', [gfg('problems/rat-in-a-maze-problem/1')]),
	'Kth Permutation Sequence': lesson('Count (n-1)! blocks. The digit is k / (n-1)!, then recurse on the rest. You do not generate n! perms.', [lc('permutation-sequence')]),
	'Single Number': lesson('XOR everything. Pairs cancel. The leftover is the unique number.', [lc('single-number')]),
	'Single Number II': lesson('Count bits mod 3, or ones/twos bit states. Linear time, constant space.', [lc('single-number-ii')]),
	'Number of 1 Bits': lesson('n &= n-1 clears the lowest set bit. Loop until n is 0. Or Python int.bit_count().', [lc('number-of-1-bits')]),
	'Counting Bits': lesson('offset = highest power of two so far. ans[i] = ans[i-offset]+1. O(n), no popcount per i.', [lc('counting-bits')]),
	'Reverse Bits': lesson('32 times: ans = (ans<<1) | (n&1); n >>= 1. Watch unsigned vs signed in Java.', [lc('reverse-bits')]),
	'Power of Two': lesson('n>0 and n&(n-1)==0. One bit set.', [lc('power-of-two')]),
	'Divide Two Integers': lesson('No / *. Subtract shifted divisors (exponential search). Watch INT_MIN / -1 overflow.', [lc('divide-two-integers')]),
	'Find XOR of Numbers from L to R': lesson('xor_upto(r) ^ xor_upto(l-1). xor_upto(n) depends on n%4 (n, 1, n+1, 0).', [gfg('problems/find-xor-of-numbers-from-l-to-r/1')]),
	'Implement Queue using Stacks': lesson('In-stack for push, out-stack for pop. Pour in→out only when out is empty. Amortized O(1).', [lc('implement-queue-using-stacks')]),
	'Valid Parentheses': lesson('Stack of opens. A close must match the top. Empty stack at the end.', [lc('valid-parentheses')]),
	'Min Stack': lesson('Stack of (value, min_so_far) or a second min-stack. Push/pop/top/getMin all O(1).', [lc('min-stack')]),
	'Next Greater Element I': lesson('Monotonic decreasing stack on nums2, map value→next greater, then look up nums1.', [lc('next-greater-element-i')]),
	'Next Greater Element II': lesson('Circular: iterate 2n and use i%n. Same decreasing stack of indices.', [lc('next-greater-element-ii')]),
	'Evaluate Reverse Polish Notation': lesson('Stack of numbers. On an operator, pop two, push the result. Token order is already postfix.', [lc('evaluate-reverse-polish-notation')]),
	'Daily Temperatures': lesson('Decreasing stack of indices. When today is warmer, pop and write the wait days.', [lc('daily-temperatures')]),
	'Largest Rectangle in Histogram': lesson('Nearest smaller left and right (monotonic stack). Height[i] * width between those bounds.', [lc('largest-rectangle-in-histogram'), tuf('data-structure/area-of-largest-rectangle-in-histogram/')]),
	'Maximal Rectangle': lesson('Treat each row as a histogram of consecutive 1s above, then histogram rectangle. O(rows*cols).', [lc('maximal-rectangle')]),
	'Car Fleet': lesson('Sort by position descending. Time to target = (target-pos)/speed. A slower time in front swallows the cars behind it.', [lc('car-fleet')]),
	'Asteroid Collision': lesson('Stack of signed sizes. Only + then - can collide. Equal size both die; smaller dies.', [lc('asteroid-collision')]),
	'Remove K Digits': lesson('Monotonic increasing stack of digits. Pop larger previous digits while k>0. Strip leading zeros.', [lc('remove-k-digits')]),
	'Sum of Subarray Minimums': lesson('Each value is min of some subarray range. Next smaller left/right gives the contribution. Mod 10^9+7.', [lc('sum-of-subarray-minimums')]),
	'Online Stock Span': lesson('Monotonic decreasing stack of (price, span). Span is 1 + popped spans while price ≥ top.', [lc('online-stock-span')]),
	'LRU Cache': lesson('HashMap key→node plus doubly linked list. Move-to-head on get/put. Evict the tail.', [lc('lru-cache'), tuf('data-structure/lru-cache-implementation/')], { complexity: 'O(1) get/put', layman: 'A dictionary to find the item, a queue to remember which one was used least recently.' }),
	'LFU Cache': lesson('Map key→node, map freq→DLL. Evict least freq, then LRU inside that freq. Update freq on every touch.', [lc('lfu-cache')]),
	'The Celebrity Problem': lesson('A celebrity is known by all and knows nobody. Shrink candidates with knows(a,b), then verify the survivor.', [gfg('problems/the-celebrity-problem/1')]),
	'Kth Largest Element in an Array': lesson('Min-heap of size k, or quickselect. Heap is n log k and safer in interviews.', [lc('kth-largest-element-in-an-array')]),
	'Top K Frequent Elements': lesson('Count, then bucket by frequency or a heap of size k. Bucket is O(n).', [lc('top-k-frequent-elements')]),
	'K Closest Points to Origin': lesson('Max-heap of size k on distance, or quickselect. Do not sort all n unless n is tiny.', [lc('k-closest-points-to-origin')]),
	'Last Stone Weight': lesson('Max-heap. Smash two heaviest, push the diff if nonzero. Last remaining (or 0).', [lc('last-stone-weight')]),
	'Task Scheduler': lesson('Idle time is driven by the most frequent task. (maxf-1)*(n+1) + count_of_maxf, then max with tasks.length.', [lc('task-scheduler')]),
	'Find Median from Data Stream': lesson('Max-heap for the lower half, min-heap for the upper. Rebalance so sizes differ by at most 1.', [lc('find-median-from-data-stream')]),
	'Kth Largest Element in a Stream': lesson('Min-heap of size k. Peek is the kth. Push and pop when size > k.', [lc('kth-largest-element-in-a-stream')]),
	'Design Twitter': lesson('Map user→tweets, user→followees. Merge latest tweets like k-way merge / heap of heads.', [lc('design-twitter')]),
	'Smallest Range Covering Elements from K Lists': lesson('Min-heap of current heads + a running max. Slide like merge-k until a list is exhausted.', [lc('smallest-range-covering-elements-from-k-lists')]),
	'Assign Cookies': lesson('Sort kids and cookies. Greedy: smallest cookie that satisfies the greediest remaining kid, or vice versa.', [lc('assign-cookies')]),
	'N Meetings in One Room': lesson('Sort by end time. Take a meeting if start ≥ last_end. Classic interval scheduling.', [gfg('problems/n-meetings-in-one-room-1587115620/1')]),
	'Jump Game': lesson('Track the farthest reachable index. If i > farthest, fail. If farthest ≥ last, success.', [lc('jump-game')]),
	'Jump Game II': lesson('BFS on the array: current window, next farthest. Jumps++ when the window ends.', [lc('jump-game-ii')]),
	'Job Sequencing Problem': lesson('Sort by profit, place each job in the latest free slot ≤ deadline. Disjoint set speeds the slot search.', [gfg('problems/job-sequencing-problem-1587115620/1')]),
	'Minimum Platforms': lesson('Sort arrivals and departures. Sweep: +1 on arrive, -1 on depart. Max concurrent is platforms.', [gfg('problems/minimum-platforms-1587115620/1')]),
	'Candy': lesson('Two passes: left-to-right for increasing ratings, right-to-left for decreasing. Answer is max of both at each child.', [lc('candy')]),
	'Insert Interval': lesson('Emit before, merge overlaps with the new interval, emit after. Sorted input.', [lc('insert-interval')]),
	'Non-overlapping Intervals': lesson('Sort by end. Count removals when start < last_end; otherwise take it. Same as scheduling.', [lc('non-overlapping-intervals')]),
	'Meeting Rooms': lesson('Sort by start. If any start < previous end, they conflict. One room cannot hold that.', [nc('meeting-schedule')]),
	'Meeting Rooms II': lesson('Min-heap of end times, or sweep +1 start / -1 end. Heap size (or max concurrent) is rooms needed.', [nc('meeting-schedule-ii')]),
	'Gas Station': lesson('If total gas < total cost, impossible. Otherwise the unique start is just after the worst prefix.', [lc('gas-station')]),
	'Fractional Knapsack': lesson('Sort by value/weight, take whole items then a fraction of the next. Greedy is correct because fractions are allowed.', [gfg('problems/fractional-knapsack-1587115620/1')]),
	'Partition Labels': lesson('Last index of each letter. Grow a partition until i == current last; then cut.', [lc('partition-labels')]),
	'Hand of Straights': lesson('Count map. Always start a group from the smallest remaining key and eat W consecutive.', [lc('hand-of-straights')]),
	'Merge Triplets to Form Target Triplet': lesson('Ignore triplets that exceed target in any coord. OR (max) the rest; check you can hit each target coord.', [lc('merge-triplets-to-form-target-triplet')]),
	'Minimum Number of Coins': lesson('If the coin system is canonical (like Indian), greedy works. Otherwise it is unbounded knapsack / Coin Change.', [gfg('problems/number-of-coins0327/1')]),
	'Binary Tree Inorder Traversal': lesson('Left, node, right. Recursion or stack. Morris threading if they ban extra space.', [lc('binary-tree-inorder-traversal')]),
	'Binary Tree Preorder Traversal': lesson('Node, left, right. Stack: push right then left so left pops first.', [lc('binary-tree-preorder-traversal')]),
	'Binary Tree Postorder Traversal': lesson('Left, right, node. Two stacks, or one stack with a last-visited pointer.', [lc('binary-tree-postorder-traversal')]),
	'Binary Tree Level Order Traversal': lesson('BFS queue. For each level, drain size() nodes. That grouping is the answer.', [lc('binary-tree-level-order-traversal')]),
	'Binary Tree Zigzag Level Order Traversal': lesson('Level order, reverse every other level (or a deque that flips direction).', [lc('binary-tree-zigzag-level-order-traversal')]),
	'Vertical Order Traversal of a Binary Tree': lesson('DFS/BFS with (col, row, val). Sort by col, then row, then value. LC is picky about ties.', [lc('vertical-order-traversal-of-a-binary-tree')]),
	'Binary Tree Right Side View': lesson('BFS and take the last node each level, or DFS right-first recording the first visit per depth.', [lc('binary-tree-right-side-view')]),
	'Maximum Depth of Binary Tree': lesson('1 + max(left, right). BFS level count also works.', [lc('maximum-depth-of-binary-tree')]),
	'Balanced Binary Tree': lesson('Height DFS that returns -1 if a subtree is unbalanced (|L-R|>1). Do not compute height twice naively.', [lc('balanced-binary-tree')]),
	'Diameter of Binary Tree': lesson('Longest path may not pass through the root. At each node, left_h+right_h is a candidate; return height up.', [lc('diameter-of-binary-tree')]),
	'Same Tree': lesson('Both null, or values equal and left/right same. Short-circuit on mismatch.', [lc('same-tree')]),
	'Symmetric Tree': lesson('Mirror: left.left vs right.right, left.right vs right.left. Queue of pairs also works.', [lc('symmetric-tree')]),
	'Invert Binary Tree': lesson('Swap left and right, recurse. BFS swap also fine.', [lc('invert-binary-tree')]),
	'Subtree of Another Tree': lesson('Same-tree at this node, or recurse left/right. Serialization + string find is a cute alternative.', [lc('subtree-of-another-tree')]),
	'Count Good Nodes in Binary Tree': lesson('DFS with max-so-far on the path. Node is good if val ≥ that max.', [lc('count-good-nodes-in-binary-tree')]),
	'Lowest Common Ancestor of a Binary Tree': lesson('If node is p or q, return it. If both sides return non-null, node is LCA. Else bubble the non-null.', [lc('lowest-common-ancestor-of-a-binary-tree')]),
	'Maximum Width of Binary Tree': lesson('BFS with indices like a heap: left=2*i, right=2*i+1. Width is last-first+1 per level. Offset indices to avoid overflow.', [lc('maximum-width-of-binary-tree')]),
	'All Nodes Distance K in Binary Tree': lesson('Build parent pointers, then BFS from target, not visiting twice. Distance k is the kth layer.', [lc('all-nodes-distance-k-in-binary-tree')]),
	'Binary Tree Maximum Path Sum': lesson('At each node, best = val + max(0,left) + max(0,right). Return up only one side (plus val).', [lc('binary-tree-maximum-path-sum')]),
	'Construct Tree from Preorder and Inorder': lesson('Preorder[0] is root. Inorder split is left/right sizes. Hash value→inorder index. Recurse.', [lc('construct-binary-tree-from-preorder-and-inorder-traversal')]),
	'Serialize and Deserialize Binary Tree': lesson('Preorder with explicit nulls, or level-order with nulls. Decode with a queue/iterator of tokens.', [lc('serialize-and-deserialize-binary-tree')]),
	'Flatten Binary Tree to Linked List': lesson('Reverse postorder: flatten right, flatten left, stitch left onto right, null left. Morris also exists.', [lc('flatten-binary-tree-to-linked-list')]),
	'Search in a BST': lesson('Walk left if target < node, right if larger. BST property, not a full scan.', [lc('search-in-a-binary-search-tree')]),
	'Insert into a BST': lesson('Walk to the null child and attach. Recursion returns the (possibly new) subtree root.', [lc('insert-into-a-binary-search-tree')]),
	'Delete Node in a BST': lesson('0/1 child: replace with the child. 2 children: replace with inorder successor (min of right), then delete that successor.', [lc('delete-node-in-a-bst')]),
	'Validate Binary Search Tree': lesson('Pass (low, high) bounds, not just left < node < right on one node. Duplicates: follow the prompt.', [lc('validate-binary-search-tree')]),
	'Kth Smallest Element in a BST': lesson('Inorder with a counter. Stop at k. Morris if they ban the stack.', [lc('kth-smallest-element-in-a-bst')]),
	'Lowest Common Ancestor of BST': lesson('Walk down: if both p and q > node, go right; both <, go left; else node is LCA. No parent pointers.', [lc('lowest-common-ancestor-of-a-binary-search-tree')]),
	'Construct BST from Preorder': lesson('Bounds: next preorder value must sit in (low, high). Consume the array with an index. O(n).', [lc('construct-binary-search-tree-from-preorder-traversal')]),
	'Two Sum IV - Input is a BST': lesson('Inorder yields a sorted array, then two pointers. Or a set while DFS.', [lc('two-sum-iv-input-is-a-bst')]),
	'Recover Binary Search Tree': lesson('Inorder should be sorted. Two nodes swapped: find the two inversions and swap values. Do not restructure.', [lc('recover-binary-search-tree')]),
	'Largest BST in Binary Tree': lesson('Postorder: each subtree reports min, max, size, and whether it is a BST. Combine if parent fits.', [gfg('problems/largest-bst/1')]),
	'Number of Provinces': lesson('DFS/BFS or union-find on the adjacency matrix. Count starts (or number of roots).', [lc('number-of-provinces')]),
	'Number of Islands': lesson('DFS/BFS flood fill each \'1\' to \'0\'. Count how many floods you start.', [lc('number-of-islands')]),
	'Flood Fill': lesson('DFS/BFS from sr,sc, recolor 4-directionally. Guard the original color == new color infinite loop.', [lc('flood-fill')]),
	'Rotting Oranges': lesson('Multi-source BFS from all rotten. Minutes = max depth. Fail if a fresh orange remains.', [lc('rotting-oranges')]),
	'01 Matrix': lesson('Multi-source BFS from all zeros. Distance to nearest 0. Do not DFS from each 1.', [lc('01-matrix')]),
	'Surrounded Regions': lesson('DFS from border \'O\'s and mark safe. Then flip remaining \'O\' to \'X\'. Interior only.', [lc('surrounded-regions')]),
	'Bipartite Graph': lesson('BFS color with 2 colors. Conflict on an edge means not bipartite. Handle disconnected graphs.', [lc('is-graph-bipartite')]),
	'Detect Cycle in Undirected Graph': lesson('DFS with parent, or union-find: a back edge to a visited non-parent is a cycle.', [gfg('problems/detect-cycle-in-an-undirected-graph/1')]),
	'Detect Cycle in Directed Graph': lesson('DFS colors (unseen/open/done). A back edge to an open node is a cycle. Kahn\'s leftover nodes also detect it.', [gfg('problems/detect-cycle-in-a-directed-graph/1')]),
	'Clone Graph': lesson('Hash old→new. DFS/BFS clone neighbors. The hash is the visited set.', [lc('clone-graph')]),
	'Max Area of Island': lesson('DFS that returns size. Track max. Mark visited so you do not double-count.', [lc('max-area-of-island')]),
	'Pacific Atlantic Water Flow': lesson('DFS/BFS from Pacific border and Atlantic border uphill. Intersection of reachable sets.', [lc('pacific-atlantic-water-flow')]),
	'Walls and Gates': lesson('Multi-source BFS from all gates (0). Fill empty rooms with distance. Walls stay -1. NeetCode hosts the premium LC.', [nc('islands-and-treasure')]),
	'Word Ladder': lesson('BFS on words, neighbors = one-letter difference. Wildcard buckets (*ot, h*t, ho*) beat scanning the whole dict.', [lc('word-ladder')]),
	'Redundant Connection': lesson('Union-find on edges in order. The first edge whose ends are already united is the extra edge.', [lc('redundant-connection')]),
	'Reconstruct Itinerary': lesson('Hierholzer: DFS, always take the smallest lexical unused edge. Reverse the postorder. Directed Euler path.', [lc('reconstruct-itinerary')]),
	'Topological Sort': lesson('Kahn (queue of indegree 0) or DFS finish times reversed. Only DAGs. Cycle ⇒ no topo.', [gfg('problems/topological-sort/1')]),
	'Course Schedule': lesson('Cycle in a directed graph? If no cycle, you can finish. Kahn or DFS colors.', [lc('course-schedule')], { layman: 'Courses are nodes, prereqs are arrows. If the arrows loop, you can never finish.' }),
	'Course Schedule II': lesson('Same as I, but emit the Kahn order (or reversed DFS). Any valid topo is accepted.', [lc('course-schedule-ii')]),
	'Alien Dictionary': lesson('Build a graph from adjacent word letter differences, then topo sort. Prefix-invalid (apple vs app) is a fail. Premium on LC.', [gfg('problems/alien-dictionary/1'), nc('foreign-dictionary')]),
	'Dijkstra\'s Algorithm': lesson('Min-heap of (dist, node). Relax neighbors. Non-negative weights only. Practice on Network Delay Time.', [gfg('problems/implementing-dijkstra-set-1-adjacency-matrix/1'), tuf('data-structure/g-35-print-shortest-path-dijkstras-algorithm/')], { complexity: 'O((V+E) log V) with a heap' }),
	'Bellman Ford': lesson('Relax all edges V-1 times. One more pass detects a negative cycle. Works with negatives, slower than Dijkstra.', [gfg('problems/distance-from-the-source-bellman-ford-algorithm/1')]),
	'Floyd Warshall': lesson('dp[k][i][j] = min via k. O(V³) all-pairs. After that, dp[i][i] < 0 means a negative cycle.', [gfg('problems/implementing-floyd-warshall2042/1')], { complexity: 'O(V³)' }),
	'Network Delay Time': lesson('Dijkstra from k. Answer is max dist, or -1 if some node is unreachable.', [lc('network-delay-time')]),
	'Cheapest Flights Within K Stops': lesson('Bellman-Ford for K+1 hops, or BFS/Dijkstra with (cost, node, stops). Do not use plain Dijkstra without stops.', [lc('cheapest-flights-within-k-stops')]),
	'Path With Minimum Effort': lesson('Binary search effort + BFS, or Dijkstra where the cost is max edge so far.', [lc('path-with-minimum-effort')]),
	'Prim\'s Algorithm': lesson('Grow MST from a node: min-heap of edges leaving the tree. Same as Dijkstra with edge weights, not path sums.', [gfg('problems/minimum-spanning-tree/1')]),
	'Kruskal\'s Algorithm': lesson('Sort edges, union-find, take if it does not form a cycle. MST weight is the sum of taken edges.', [gfg('problems/minimum-spanning-tree/1')]),
	'Min Cost to Connect All Points': lesson('Complete graph of Manhattan distances, then Prim or Kruskal. Prim + heap is the usual LC path.', [lc('min-cost-to-connect-all-points')]),
	'Number of Operations to Make Network Connected': lesson('If extra cables ≥ components-1, answer is components-1. Union-find counts both.', [lc('number-of-operations-to-make-network-connected')]),
	'Accounts Merge': lesson('Union emails that share an account, then group. Union-find on emails, map email→name.', [lc('accounts-merge')]),
	'Critical Connections in a Network': lesson('Tarjan bridges: disc/low. A bridge is an edge u-v with low[v] > disc[u].', [lc('critical-connections-in-a-network')]),
	'Kosaraju Strongly Connected Components': lesson('DFS finish order, reverse the graph, DFS in that order. Each second-DFS tree is an SCC.', [gfg('problems/strongly-connected-components-kosarajus-algo/1')]),
	'Climbing Stairs': lesson('Fibonacci. dp[i] = dp[i-1]+dp[i-2]. Two variables, not an array.', [lc('climbing-stairs'), tuf('data-structure/dynamic-programming-climbing-stairs/')]),
	'House Robber': lesson('For each house: skip (keep prev) or take (prev2 + nums[i]). Linear DP.', [lc('house-robber')]),
	'House Robber II': lesson('Circular: max of rob [0..n-2] and rob [1..n-1]. Reuse House Robber.', [lc('house-robber-ii')]),
	'Unique Paths': lesson('Combinations C(m+n-2, m-1), or DP grid. Obstacle-free.', [lc('unique-paths')]),
	'Unique Paths II': lesson('Same DP, zeros on obstacles. First row/col can be blocked for everything after.', [lc('unique-paths-ii')]),
	'Minimum Path Sum': lesson('dp[i][j] = grid + min(up, left). Can compress to one row.', [lc('minimum-path-sum')]),
	'Triangle': lesson('Bottom-up: each cell += min of the two children. Mutate the triangle or a 1D array.', [lc('triangle')]),
	'Minimum Falling Path Sum': lesson('Each cell += min of the 2–3 cells above (j-1,j,j+1). Watch bounds.', [lc('minimum-falling-path-sum')]),
	'Decode Ways': lesson('A digit may pair with the previous if 10–26. Zero is only valid as 10 or 20. DP on index.', [lc('decode-ways')]),
	'Coin Change': lesson('Unbounded knapsack: min coins to make amount. dp[x] = min(dp[x-coin])+1. Impossible stays inf.', [lc('coin-change')]),
	'Coin Change II': lesson('Count combinations, not permutations. Loop coins outer so order does not duplicate.', [lc('coin-change-ii')]),
	'Word Break': lesson('dp[i] true if some word ends at i and dp[start] was true. A set of words. Trie if the dict is huge.', [lc('word-break')]),
	'Longest Increasing Subsequence': lesson('Patience: tails array + binary search. O(n log n). O(n²) DP is the interview fallback.', [lc('longest-increasing-subsequence'), tuf('data-structure/longest-increasing-subsequence-dp-41/')], { complexity: 'O(n log n) patience, O(n²) DP' }),
	'Palindromic Substrings': lesson('Expand around centers, count every palindrome, not just the longest. DP boolean table also works.', [lc('palindromic-substrings')]),
	'Partition Equal Subset Sum': lesson('0/1 knapsack: can you make sum/2? Bitset or boolean DP on the target.', [lc('partition-equal-subset-sum')]),
	'0/1 Knapsack': lesson('Each item once. dp[w] from the back so you do not reuse an item. GFG classic.', [gfg('problems/0-1-knapsack-problem0945/1')]),
	'Unbounded Knapsack': lesson('Items reusable. Loop weights forward, or coins-outer like Coin Change II.', [gfg('problems/knapsack-with-duplicate-items4201/1')]),
	'Target Sum': lesson('Assign +/−. Equivalent to partition: find a subset with (total+target)/2. Then 0/1 knapsack count.', [lc('target-sum')]),
	'Longest Common Subsequence': lesson('dp[i][j] = diag+1 on match, else max(left, up). Strings 1-indexed in the table.', [lc('longest-common-subsequence')]),
	'Edit Distance': lesson('Insert/delete/replace. dp[i][j] = min of those three. Match → copy diagonal.', [lc('edit-distance')]),
	'Wildcard Matching': lesson('\'?\' one char, \'*\' any sequence. DP: star can eat 0 chars (up) or 1+ (left). Greedy two-pointer also exists.', [lc('wildcard-matching')]),
	'Interleaving String': lesson('dp[i][j] if s3 prefix is an interleave of s1[:i] and s2[:j]. Use the last char to pick which string advanced.', [lc('interleaving-string')]),
	'Distinct Subsequences': lesson('How many ways t is a subsequence of s. dp[i][j] += match diagonal. Loop carefully to not overwrite.', [lc('distinct-subsequences')]),
	'Best Time to Buy and Sell Stock II': lesson('Sum every uphill. Equivalent to unlimited transactions without cooldown.', [lc('best-time-to-buy-and-sell-stock-ii')]),
	'Best Time to Buy and Sell Stock with Cooldown': lesson('States: hold, sold, rest. Rest[i] = max(rest[i-1], sold[i-1]); you cannot buy the day after selling.', [lc('best-time-to-buy-and-sell-stock-with-cooldown')]),
	'Best Time to Buy and Sell Stock III': lesson('At most two transactions. Track firstBuy, firstSell, secondBuy, secondSell. Or DP k=2.', [lc('best-time-to-buy-and-sell-stock-iii')]),
	'Longest Increasing Path in a Matrix': lesson('DFS + memo: from a cell, walk to strictly larger neighbors. The DAG of values has no cycles.', [lc('longest-increasing-path-in-a-matrix')]),
	'Burst Balloons': lesson('MCM-style: dp[l][r] is max coins bursting inside (l,r). Last balloon k in that range scores nums[l]*nums[k]*nums[r].', [lc('burst-balloons')]),
	'Regular Expression Matching': lesson('\'.\' one char, \'*\' previous-char 0+ times. DP: star is empty (skip two pattern chars) or eat one text char.', [lc('regular-expression-matching')]),
	'Matrix Chain Multiplication': lesson('dp[i][j] min cost to multiply mats i..j. Try last split k. GFG array is dimensions, not matrices.', [gfg('problems/matrix-chain-multiplication0303/1')]),
	'Maximal Square': lesson('dp[i][j] = side of square ending here = 1+min(left, up, diag) if matrix is 1. Track max side².', [lc('maximal-square')]),
	'Palindrome Partitioning II': lesson('Min cuts so every piece is a palindrome. Palindrome table + dp cuts. Related to the backtracking version.', [lc('palindrome-partitioning-ii')]),
	'Implement Trie (Prefix Tree)': lesson('Node with 26 children + isWord. Insert/search/startsWith all O(length). Draw one node per character.', [lc('implement-trie-prefix-tree'), tuf('data-structure/implement-trie-1/')]),
	'Design Add and Search Words Data Structure': lesson('Trie + DFS on \'.\'. Branch all 26 children when you see a dot. Keep search from blowing the stack on long words.', [lc('design-add-and-search-words-data-structure')]),
	'Word Search II': lesson('Build a trie of words, DFS the board, prune dead prefixes, mark found words so you do not emit twice.', [lc('word-search-ii')]),
	'Maximum XOR of Two Numbers in an Array': lesson('Bit trie from MSB. For each number, walk the opposite bit when it exists. That maximizes XOR.', [lc('maximum-xor-of-two-numbers-in-an-array')]),
	'Count Distinct Substrings': lesson('Insert every suffix into a trie; new nodes = new distinct substrings. Suffix array is the heavy version.', [gfg('problems/count-of-distinct-substrings/1')]),
	'Longest String with All Prefixes': lesson('Trie with isWord. The winner is the longest word whose every prefix is also a word. Sort + set also works.', []),
	'Timed easy: 20 minutes, no editor notes': lesson('Pick an Easy from NeetCode 150. Timer on, blank editor, talk the brute force then code. Stop at 20 even if you fail — log the miss for tomorrow.', []),
	'Timed medium: 35 minutes, talk out loud': lesson('One Medium, 35 minutes, narrate pattern and complexity before typing. If you are stuck at 15, state brute force and only then optimize.', []),
	'Redo a missed problem the next day from memory': lesson('Open a blank file. No yesterday\'s notes. If you cannot rebuild it, the pattern is not yours yet — that is the point of the 1-day revise box.', []),
	'Write brute force then optimal for one graph problem': lesson('Islands, course schedule, or rotting oranges. Write the naive version, then BFS/union-find. Interviews buy the first 3 minutes of brute force.', []),
	'Mock interview: 45 minutes with a friend or pramp-style': lesson('45 minutes, one medium, your mouth first. Pramp, a friend, or a rubber duck with a recording. Heatmap does not count this unless you Complete a tagged lesson.', []),
	'Redo 5 Blind-75 problems from memory in one sitting': lesson('Five from https://leetcode.com/problem-list/oizxjoit/ (Blind 75). No hints. Mark Again on Revise for any miss.', []),
	'Explain one DP (LIS or knapsack) on a whiteboard': lesson('State, transition, base, complexity, then a 5-cell dry run. If you cannot say the state in one sentence, do not code yet.', []),
};
